### ISSUE TITLE
Shower selection issues with PyTables

### ISSUE THREAD

**Issue by 153957** [HiSPARC/sapphire#116]
The data server was getting very full so I tried to remove some of the regenerable CORSIKA data, the DAT00000 file. But only for small showers, since those are very easy ands fast to recreate. Unfortunately due to some PyTables bug I accidentally removed to many..

The following code was used, intending to remove the DAT00000 data for tiny showers.
```python
import os

from sapphire import CorsikaQuery

PATH = '/data/hisparc/corsika/data/%s/DAT000000'
RESULT_PATH = '/data/hisparc/corsika/data/%s/corsika.h5'
cq = CorsikaQuery('/data/hisparc/corsika/corsika_overview.h5')
small_sims = cq.sims.read_where('log10(energy) < 12')
seeds = ('%d_%d' % (sim['seed1'], sim['seed2']) for sim in small_sims)
for seed in seeds:
    path = PATH % seed
    check_path = RESULT_PATH % seed
    if os.path.exists(check_path):
        try:
            os.remove(path)
        except:
            print path
            break
```

However, the read_where query does not seem to work properly, it selected larger showers as well.
```python
log10(small_sims[:10]['energy'])
# array([ 16.,  13.,  13.,  13.,  16.,  17.,  16.,  16.,  16.,  15.], dtype=float32)
```
Reversing the sign in the query gives a similar result:
```python
large_sims = cq.sims.read_where('log10(energy) > 12')
log10(large_sims[:10]['energy'])
# array([ 14.,  14.,  16.,  15.,  15.,  16.,  15.,  15.,  13.,  15.], dtype=float32)
```

So, unfortunately also some large shower files were removed, fortunately the `corsika.h5` data still exists, so no data was lost (I prevented the removal of DAT0000 if no corsika.h5 existed). Also all input files were saved, so rerunning simulations should be easy, but unnecessary.

Perhaps an update of PyTables/Cython/NumExpr will fix this bug.. or did I make a typo somewhere..?

**Comment by tomkooij** [comment]
Ouch! Might be related to #114 

numexpr ```log10()``` might be the culprit in this case as well. The query works without ```log10()```:  

``` 
cq.sims.read_where('energy > 1e14')['energy']
array([  1.00000000e+14,   1.00000003e+16,   1.00000000e+14, ...,
         9.99999984e+17,   9.99999984e+17,   9.99999984e+17], dtype=float32)
```

**Comment by 153957** [comment]
Ok, hmm that is very annoying. Also the proposed fix in https://github.com/HiSPARC/sapphire/commit/4eb8203908fb7261b034f5671f3d092a6f21a3e7 does not resolve this issue. The `/data/hisparc/env/miniconda/envs/hisparc` env is using the latest 'good' (https://github.com/HiSPARC/publicdb/issues/131) version of numexpr, v2.4.6..

On my Mac with numexpr version 2.4.4 the query works as expected.

**Comment by tomkooij** [comment]
I tested using: https://gist.github.com/tomkooij/5e879f55aad637545a68 (This should return >40k)

**numexpr 2.4.6 is broken:**
```
(test)tkooij@stbc-i1:[/data/hisparc/tom]: python test_read_where.py
tables version:  3.2.2
numexpr version:  2.4.6
4818
```

numexpr 2.4.4 works:
```
(test)tkooij@stbc-i1:[/data/hisparc/tom]: python test_read_where.py
tables version:  3.2.2
numexpr version:  2.4.4
43386
```

(numexpr 2.4.5 does not exist.)

**Comment by 153957** [comment]
Tested with Numexpr 2.5
```
tables version:  3.2.2
numexpr version:  2.5
4509
```
I used a different `corsika_overview.h5`, which might explain the difference between your `4818` result. But the result is still wrong.

**Comment by 153957** [comment]
Reported to Numexpr https://github.com/pydata/numexpr/issues/210

**Comment by tomkooij** [comment]
ARGH!

This can easily be fixed using a locally installed (and compiled) numexpr.
I tried ```2.5.1dev0``` and ````2.4.6 (commit b813190) ``` ** both are fine**

The conda package seems broken. 

BTW, This is my test program: https://gist.github.com/tomkooij/c8d2e0c0a1a8444e16c0a1a271e7b747

In the broken (conda) version a table.read() does not work, but a recarray with the same values works. The numpy.ndarrays have the same type, dtypes, the same MD5, but still NumExpr handles them differently. :-1:

**Comment by 153957** [comment]
Thanks for investigating! Hopefully they will fix the conda builds..
