### ISSUE TITLE
qsub_store_corsika jobs sometimes fail because they cant find store_corsika

### ISSUE THREAD

**Issue by 153957** [HiSPARC/sapphire#117]
Some jobs exit with this in the log;

> ......nikhef.nl.SC: line 4: store_corsika_data: command not found

Possibly due to failing to activate the corsika env; `source activate corsika &> /dev/null`
But since the output of that command is ignored it is not yet clear if an error there is the cause.

Sorting the logs by date/time shows that the success/fails are grouped in time, perhaps they fail if to many jobs are already working causing a high (I/O) load on trave (/data/hisparc).

Could try to use the full path to the store script in the command:
`store_corsika_data [...]DAT00000 [...]corsika.h5`
i.e.
`/data/hisparc/env/miniconda/envs/corsika/bin/python /data/hisparc/env/miniconda/envs/corsika/bin/store_corsika_data [...]DAT00000 [...]corsika.h5`

**Comment by tomkooij** [comment]
If it's really a timeout / high load on trave, I think we can best ignore (retry failed jobs) and not be bothered with editting the script.

If you want to edit the script, the only real solution (IMHO) is actually checking for the enviroment to be activate and retrying.

I would not invest time in a solution that only solves half the problem. (That's what I always end up doing: It does not work)

**Comment by 153957** [comment]
I replaced the command to use the full path to python and the script, that seemed to help..

**Comment by 153957** [comment]
Fixed in a7bc7e458477d5db4605c50b748bff53c9d12efe
