### ISSUE TITLE
Allow Station objects for test stations

### ISSUE THREAD

**Issue by 153957** [HiSPARC/sapphire#127]
Currently this does not work:

```python
from sapphire import Station
Station(599)
```

It is a valid station with event and config data, it is however a test station.
Currently the init of Station checks if the station number is valid, in order to immediately give an exception if the station number is invalid. However, the list of station numbers from `Network.station_numbers()` excludes test stations.

Possible solutions:
- Check validity of station number differently
- Add optional argument to stations (and thus station numbers) to include all stations (also test stations)

This is currently a problem for the publicdb which uses Station objects to get trigger settings for the processing of events.

**Comment by 153957** [comment]
For now I changed the Exception (in case of 'bad' station number) to a warning.
I do not recall perfectly why I added the station number check with an Exception,
but stations without any configurations are likely to fail when calling one of the methods.

**Comment by tomkooij** [comment]
But what about typo's? (non-existant stations):

```
In [2]: s = Station(599)
/data/hisparc/tom/sapphire/sapphire/api.py:526: UserWarning: Possibly invalid station, or without config.
  warnings.warn('Possibly invalid station, or without config.')

In [3]: s = Station(1599)

In [4]:
```
599 throws a warning, but 1599 is fine?
```Station(1599).gps_locations``` throws an Exception ofcourse, but IMHO the __init__ should fail.

**Comment by 153957** [comment]
I thought about that, but it would mean implementing an extra API call on the publicdb.
Currently requesting a list of stations includes only non-test stations with at least one (valid, i.e. no (0,0,0) GPS coordinates) configuration. An option could be added to include test stations. That would make more sense, but this was a quicker fix.
I know it will only warn once, since additional warnings would be identical. This could be remedied by including the station number in the warning, but I don't like to be spammed by warnings.. I agree that this can be confusing...

**Comment by tomkooij** [comment]
It seems ok to leave this as is. Closing.
