### ISSUE TITLE
Fix altitude correction for station pairs far from ENU origin

### ISSUE THREAD

**Issue by 153957** [HiSPARC/sapphire#142]
For example the altitude difference for stations 8004-8009 is different when 501 is used as ENU origin then when 8004 is used.

```python
from sapphire import HiSPARCStations
cluster = HiSPARCStations([501, 8004, 8009])
cluster.calc_rphiz_for_stations(1, 2)[-1]
# -8.488  (about 28 ns)
cluster = HiSPARCStations([8004, 8009])
cluster.calc_rphiz_for_stations(0, 1)[-1]
# -18.730  (about 62 ns)
```

When determining station timing offset the same cluster is used for each offset (i.e. station pair). The cluster object is created in the init of the DetermineStationTimingOffsets class. In the publicdb jobs a DetermineStationTimingOffsets object is created with all stations with data in a network summary... This can result in unexpected offsets.

Perhaps the altitude correction should not be performed in the calibration.
Or we should ensure that local coordinates are used, and that the same reference is used for the direction reconstructions...

**Comment by 153957** [comment]
see that altitude differences are also not accounted for for detector timing offsets.
The function in sapphire (determine_detector_timing_offsets) supports a station as argument which is used to determine detector altitude differences. However, this is not used by the esd.determine_detector_timing_offsets_for_summary function in the publicdb. This also explains the large difference in offsets for detectors 1, 3, and 4 relative to 2 (red) for the FOM station ( http://data.hisparc.nl/show/stations/1009/config/ ), since detector 2 is several floors lower than the rest.

@davidfokkema @tomkooij , Your ideas on this?

**Comment by tomkooij** [comment]
We should fix the altitudes for different origins (is the difference due to curvature of the earth?) and include altitude corrections in both detector and station timing offsets.

**Comment by 153957** [comment]
Yes, due to curvature. Currently I think 501 or some other low number station was used as reference, the ENU plane is then defined at that location. For stations with a very different longitude/latitude the plane will not represent the local-ENU plane. So the definition of 'Up' is different.

**Comment by davidfokkema** [comment]
The only reason to use ENU is because a plane is a nice approximation to the surface of the Earth in a not too large area. If we need hacks to make it work over a large area maybe we should just resort to x,y,z-coordinates? Or use ENU for each cluster, with a different reference.

**Comment by 153957** [comment]
Side note: this also means that the detector altitude for detector 2 at FOM is probably incorrect. The offset is around 47 ns. ie. 47 ns * 0.3 m/ns = 14.1 m. While the altitude difference is 15.6 m, the location of detector 2 was approximated by me using knowledge of its location in the building and Google Maps/Street View..

**Comment by 153957** [comment]
In this case we can easily fix it by simply defining a cluster object for the two stations in question. For coincidence reconstructions a similar approach may be needed, or we should at least store the reference lla in the reconstruction table, as noted in #92.

**Comment by 153957** [comment]
For publicdb jobs this should be fixed by https://github.com/HiSPARC/publicdb/commit/6c93eda46d863be726227a38147d3982bbb342c9

**Comment by 153957** [comment]
For detector offsets it is fixed in https://github.com/HiSPARC/publicdb/commit/c9ca600e1999e8834d9529f6645d6a5969a118e2 ..

(not tested yet)

Note that this does mean that updated station layouts will mean that detector (and station) offsets need to be recalculated.

**Comment by 153957** [comment]
Detector offsets for station 507 and 1009 (which have a detector at different altitude from other detectors) have been recalculated and are now closer together. There is still a remaining offset for the FOM station which may be explained by the uncertainty of the detector altitude.

**Comment by 153957** [comment]
Offsets will be recreated soon.
