### ISSUE TITLE
many NaN station timing offsets for subcluster [102, 104, 105] 

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/sapphire#147]
The station timing offsets for subcluster [102, 104, 105] are all NaN in december 2015 (and maybe much of 2015) while there seems to be data for the stations.

I have not investigated.

**Comment by 153957** [comment]
Partly related for the mentioned cluster, but at different time period.
Station 102 uses/used PySPARC for most of of 2015, unfortunately the timestamps were incorrectly calculated, that data probably has less coincidences than expected.
https://github.com/HiSPARC/datastore/issues/9
