### ISSUE TITLE
Python 3.x version support

### ISSUE THREAD

**Issue by 153957** [HiSPARC/sapphire#158]
Which version of Python 3.x should we aim to support?
In case some slightly older versions of 3 should also be supported
they should be added to the Travis test matrix.

Or should we only support the latest? (currently 3.5) (I vote for this.)

Given that we currently also support Python 2.7 it is unlikely
that older versions of Python 3 are not supported.
But to prevent making it to difficult for ourselves, lets keep the support narrow.
Mostly depending on wether the dependencies also support the latest
Python 3 version.

(@davidfokkema @tomkooij @kaspervd)

**Comment by tomkooij** [comment]
+1 for supporting only the latest version. However, testing against the previous version is probably a good idea. (Testing != supporting). Once 3.6 get's released it makes sense to test against 3.5 and 3.6 for a while. 

As for depencies: PyTables 3.3.0 requires python>=3.4. We need that for unpickling objects stored in node attributes between python 2/3.

**Comment by davidfokkema** [comment]
+1 for Arne's proposal and Tom's amendment.

**Comment by kaspervd** [comment]
So we agree to only support Python 3.5 once we've updated everything

**Comment by 153957** [comment]
Nope, also keep Python 2.7 support for now (EOF is in 2020). And some users (students) may have a hard time to install Python 3. So keep Python 2 for now.

Concerning Python 3 versions to support; yes, aim for the current version. Let Travis keep track of older versions, if they can easily be supported, that is fine.
