### ISSUE TITLE
Make coincidence ESD tests more stable

### ISSUE THREAD

**Issue by 153957** [HiSPARC/sapphire#164]
Mock the API to prevent using the latest Network data form the server, which might not match to the data used to create the 'expected' test data.
Currently the tests fail each time a station is added, until the test data is updated.

Example:
https://travis-ci.org/HiSPARC/sapphire/jobs/197125770

**Comment by tomkooij** [comment]
+1 !

**Comment by davidfokkema** [comment]
+1 !

**Comment by tomkooij** [comment]
Ok, Let's fix this once and for all: I'll do this next monday (Feb 6th).
