### ISSUE TITLE
Corsika sapphire.GroundParticlesSimulation() ignores gamma's

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/sapphire#40]
Currently the get_particles_in_detector() method of sapphire.GroundParticlesSimulation() only searches for electrons and muons. Gamma's (particle_id==1) are ignored.

In HiSPARC detector stations we detect events consisting of 3 gamma's or 2 charged particles and 2 gamma's. These events are not recovered from the Corsika simulations.

In detector.py there is an algorithm implemented for calculation the detector response. (method simulate_detector_mip() )
- An algorithm for gamma's is not implemented
- The algorithm for charged particles is not documented. Source?

**Comment by 153957** [comment]
The commits adding docstrings to the signal and transport time for mips have been added to master.
And Tom opened a pull request for the gamma response #54
