### ISSUE TITLE
Improve celestial transformations

### ISSUE THREAD

**Issue by 153957** [HiSPARC/sapphire#52]
As noted in 0bd09e46d31766ec1ac6d1b3338031ac5e6163da there is still a difference between the results from SAPPHiRE, AstroPy, and PyEphem. Where does this come from?

We should identify the cause of the differences.

Some places to look:
- [Astropy - cirs_observed_transforms.py](https://github.com/astropy/astropy/blob/master/astropy/coordinates/builtin_frames/cirs_observed_transforms.py)
- [Essential Routines for Fundamental Astronomy](https://github.com/liberfa/erfa)

**Comment by 153957** [comment]
Less of a difference now that we correctly convert sexagesimal to decimal (c54b81fe99fa198007f7555ac428f2506653329e)

Still a difference left.

- Check GPS -> LST (astropy.time.Time, both 'mean' and 'apparent')
- ..

**Comment by kaspervd** [comment]
They should ideally be in the order of arcseconds (see [the benchmarks](http://www.astropy.org/coordinates-benchmark/summary.html)). Is it an idea to simply use AstroPy? Their conversion already relies on [ERFA](https://github.com/liberfa/erfa) (Essential Routines for Fundamental Astronomy).

**Comment by 153957** [comment]
When we started to implement the transformations module AstroPy did not yet perform the transformations we were interested in. Now they do. When last I checked the documentation was fairly bad, and there were some bugs in some transformations. Im certain those have been resolved by now. Since NumPy appears to be the only (non-optional) requirement for AstroPy, and NumPy is already installed for SAPPHiRE it should be fairly easy to install. Moreover, a conda package is available for even easier installs.

**Comment by tomkooij** [comment]
We can **use** astropy transformations in our example notebooks etc.  And perhaps flag our own transformations as deprecated. Throw a `DepractionWarning` and maybe point to astropy.

We are not going to depend on astropy as in making astropy a requirement in `setup.py` are we?

**Comment by 153957** [comment]
Do you have an objection to that?
It could be useful to update the transformations module to use AtroPy.
This is easier than giving some examples, since some of the hard work can be taken care of.

**Comment by tomkooij** [comment]
astropy is not pure python and at the moment there a no windows wheels on PyPI. `Hence `pip install astropy` fails on windows. However since it's in anaconda we perhaps should not worry and just include it.

I'll try to play with astropy's transformations and make up my mind.

**Comment by 153957** [comment]
Good reason! I was indeed worrying about all the C code in there. It will likely be difficult for users with Pythonx,y or some other strange Python installation to get it working..

We could make it optional, if available use it, if not use less accurate fallbacks..

**Comment by tomkooij** [comment]
tagging @SBeijen as a principal user of these transformations.

**Comment by davidfokkema** [comment]
@153957 I think we shouldn't introduce multiple code paths. If we make it optional, a fallback should be very explicit, I think.

**Comment by 153957** [comment]
> Explicit is better than implicit.

😉

**Comment by davidfokkema** [comment]
Haha, exactly!

**Comment by 153957** [comment]
Fixed in #175
