### ISSUE TITLE
Determine station(/detector) timing offsets over time

### ISSUE THREAD

**Issue by 153957** [HiSPARC/sapphire#58]
For detectors it is easy, one day of data is enough to determine the offsets.
For stations it required more data, depending on the distance between the two stations.

We could make a timestamped list, like the csv sources for the publicdb histograms, then use something like `bisect.bisect_right` to easily find the value that is relevant for a given event..

Perhaps detector timing offset determination should be added to the Publicdb (ESD) jobs.
And accesible via the API (or source csv)..

I'm working on station timing offset determination and looking at the changes over time. And how much data is required for good fits (depending on station distance and other factors).

**Comment by 153957** [comment]
Detector offsets are automatically determined each day and made available through the 'Source csv's.
Station offsets are not yet automatically determined.

**Comment by 153957** [comment]
@tomkooij

**Comment by tomkooij** [comment]
Yes. I would be nice to have that while tinkering with an algorithm that processes the results of the fit.

I'm trying to figure out how to handle "intervals" between GPS and/or configuration changes. (Or a timeinterval in general). What if the interval is too small? Use offset determined in next interval? Try to reconstruct from nearby stations? 
When is a fitted offset "correct"? Use quality of the fit? Cross check nearby stations?

**Comment by tomkooij** [comment]
See also HiSPARC/publicdb#133.
