### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by 153957** [HiSPARC/sapphire#64]
Should we provide easier importing for 'common' classes?
Similar to many other packages, including artist.

Something like this (in `sapphire.__init__`):

```python
from .esd import quick_download, download_data, download_coincidences
from .clusters import HiSPARCStations
from .analysis.reconstructions import (ReconstructESDEvents,
                                       ReconstructESDCoincidences)
```

Yes/no, more/less/other classes/functions?

**Comment by davidfokkema** [comment]
YES

**Comment by tomkooij** [comment]
Yes!

Are you adding all those functions to "__all__" as well?? 
To keep ```from sapphire import *``` consistent ?

**Comment by 153957** [comment]
Of course, because otherwise pyflakes would complain that the imported functions/classes are not used :)

**Comment by 153957** [comment]
Further discussion in #65
