### ISSUE TITLE
esd module assigns wrong 'event_ids'

### ISSUE THREAD

**Issue by 153957** [HiSPARC/sapphire#67]
All event_ids currently become 0, instead of the row number. This is because of the changes in 892456b766408b1837113235ecccdcad3f5ebfc0
If a `table.flush()` is added after the `row.append()` it works correctly again.
But check the performance first, perhaps we should just check the existing length at start and the manually increment/enumerate from there. Or normalize the event_ids afterwards like in [`process_events`](https://github.com/HiSPARC/sapphire/blob/master/sapphire/analysis/process_events.py#L229)

**Comment by tomkooij** [comment]
Write / add a test first?

**Comment by 153957** [comment]
There is a test (6baaed2646cab3e49f6450ed23e007052926e235) to compare the results to a generated sample, similar to the simulations.

Unfortunately I made it after the other commit, and other data rows were fine.
On my local copy I have updated the test file with the correct event_ids, so the test fails for the current esd module. It works when I added the flush(), but I have not yet tested its current performance.

**Comment by 153957** [comment]
Fixed in 1580c44, unfortunately this negates the performance gains..
Self incrementing the ids should also work, but requires some extra care to properly implement for downloading coincidences..

**Comment by tomkooij** [comment]
Perhaps self-incrementing can be made robust by transforming _readline_and_write() into a context manager that uses len(table) on setup, increments an internal counter at each call and, flushes the tables on exit.

I'll check to see if I can make it work.

**Comment by tomkooij** [comment]
Imlemented in #68.

Passes the test, but speed not tested.
