### ISSUE TITLE
Stuck simulations

### ISSUE THREAD

**Issue by 153957** [HiSPARC/sapphire#74]
@montanush reported that the GroundParticlesSimulation gets stuck sometimes (in the same place when rerunning the same shower, with same seed).

I ran ~100 different simulations on Stoomboot, ~30 got stuck and never finished.
I added the `import pdb; pdb.set_trace()` line to interrupt running when the simulation had progressed to the iteration where it got stuck.

After stepping through the code it finally got stuck here:
```
> /Users/arne/Dropbox/hisparc/Code/sapphire/sapphire/simulations/base.py(103)simulate_events_for_shower()
-> for station_id, station in enumerate(self.cluster.stations):
(Pdb) n
> /Users/arne/Dropbox/hisparc/Code/sapphire/sapphire/simulations/base.py(105)simulate_events_for_shower()
-> self.simulate_station_response(station, shower_parameters)
(Pdb) n^C^\
Quit: 3
```
I had to kill the process in the end to get out of the stuck state.
The program was using a lot of CPU, so it seemed to be doing something.. it did not respond to ^C, I had to kill it with ^\\.
Unfortunately I was stepping through the code with n, not s, otherwise I might know more accurately where it got stuck.
I will try to do that.

I did record the state of the pseudo random number generators, so I should be able to set the generators such that I don't have to wait another ~28k loops.

**Comment by 153957** [comment]
Using the `setstate` and `set_state` I did get the expected shower parameters but during debugging the execution did not get stuck..

**Comment by tomkooij** [comment]
too bad! Nasty bug...

**Comment by 153957** [comment]
I tried again the long way, but got a kernal panic (probably unrelated), restarting...

**Comment by 153957** [comment]
This time it hang during read_where:
```
> /Users/arne/Dropbox/hisparc/Code/sapphire/sapphire/clusters.py(48)get_xy_coordinates()
-> def get_xy_coordinates(self):
(Pdb) r
--Return--
> /Users/arne/Dropbox/hisparc/Code/sapphire/sapphire/clusters.py(50)get_xy_coordinates()->(310.04083964404884, 34.010616134738228)
-> return x, y
(Pdb) s
> /Users/arne/Dropbox/hisparc/Code/sapphire/sapphire/simulations/groundparticles.py(227)get_particles_in_detector()
-> detector_boundary = sqrt(.5) / 2.
(Pdb) s
> /Users/arne/Dropbox/hisparc/Code/sapphire/sapphire/simulations/groundparticles.py(228)get_particles_in_detector()
-> query = ('(x >= %f) & (x <= %f) & (y >= %f) & (y <= %f)'
(Pdb) s
> /Users/arne/Dropbox/hisparc/Code/sapphire/sapphire/simulations/groundparticles.py(230)get_particles_in_detector()
-> (x - detector_boundary, x + detector_boundary,
(Pdb) s
> /Users/arne/Dropbox/hisparc/Code/sapphire/sapphire/simulations/groundparticles.py(231)get_particles_in_detector()
-> y - detector_boundary, y + detector_boundary))
(Pdb) s
> /Users/arne/Dropbox/hisparc/Code/sapphire/sapphire/simulations/groundparticles.py(232)get_particles_in_detector()
-> return self.groundparticles.read_where(query)
(Pdb) s
--Call--
> /Users/arne/miniconda/lib/python2.7/site-packages/tables/table.py(1552)read_where()
-> def read_where(self, condition, condvars=None, field=None,
(Pdb) r
```

**Comment by tomkooij** [comment]
I tested a different simulation this morning: I got an empty list from the read_where query in the iteration that "locks up". I was going to save the PRNG state, but you beat me to it. :+1:  

This is not going to be easy... Especially since restoring the PRNG does not reproduce the problem. Something inside pytables? Some memory leak / garbage collection issue in python? no fun!

**Comment by davidfokkema** [comment]
Maybe it does not *hang*. Maybe it is stuck in a very long, or infinite, loop. Or maybe I do not quite understand how you use the debugger and it *does* sometimes hang. If the latter, might it be the filesystem?

**Comment by tomkooij** [comment]
Just a thought: Didn't this bug appear after sorting!? Perhaps retry on a unsorted and/or not CSIindexed corsika.h5?

**Comment by 153957** [comment]
It hangs every time if I don't try anything fancy.
Originally the simulation ran on Stoomboot, it got stuck at iteration 28876 (28875 rows were saved to the coincidences tables). The simulation kept running until its 48 hrs were up. I restarted the job on an interactive Stoomboot machine (screen), it also got stuck, I tried to do a Keyboard interrupt (^C) but that gave no response (even after several minutes), meanwhile Python was using 100% CPU.

Next I copied the shower file to my Mac, the simulation got stuck at the same place again. So I tried inserting the Python debugger to find out if there were weird things happening (or perhaps shower core on a detector causing slow performance) but I only found it was stuck in `simulate_station_response`.
I did capture the random generator states (in the loop of the `generate_shower_parameters`), so in the next run I set the random states at the start of the `generate_shower_parameters` method to those states. But then it did not crash (it didn't get stuck).. So then I went back to the original plan and now used 'step' more often to hopefully find the line that was causing the problem, not expecting it to be in PyTables I tried skipping it by making `read_where` go directly to its `return`, but then it got stuck.. (not directly, but for one of the detectors for 509).

CORSIKA simulation: 867099566_793958448

Simulation script:
```python
import warnings

import tables

from sapphire import HiSPARCStations, GroundParticlesSimulation

if __name__ == "__main__":
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        cluster = HiSPARCStations([501, 502, 503, 504, 505, 506, 508, 509,
                                   510, 511])
    corsika_path = 'corsika.h5'

    with tables.open_file('result.h5', 'w') as result:
        sim = GroundParticlesSimulation(
            corsikafile_path=corsika_path, max_core_distance=1006.58,
            cluster=cluster, datafile=result, output_path='/', N=100000,
            seed=153957, progress=False)
        sim.run()
        sim.finish()
```

**Comment by 153957** [comment]
@tomkooij Im not certain, I might rerun this simulation with the unsorted version it 'should' not take to much longer, since it is a fairly small shower (<5 MB)

**Comment by 153957** [comment]
Stuck at same iteration with the unsorted corsika.h5..

**Comment by tomkooij** [comment]
This is awful. Stuck on the same query even with datafile in different order. Stuck on different machine. But *only* stuck after >1hour of computation.

Whats next? Use pdb to step into read_where() instead of stepping over it?

**Comment by 153957** [comment]
I did step through `read_where` (accidentally) several times while debugging and that resulted in many many lines of code to step through.. so it will take quite some effort to find the problematic code..
Well at least now I know exactly during which iteration (i = 28876) and which station (509) the problem occurs..

**Comment by tomkooij** [comment]
I'm totally unfamiliar with pdb with it seems you can actually catch SIGQUIT (ctrl-\) and SIGXCPU (cpu time limit exceed) with python and start debugger:

````
import signal
import resource

def  int_handler(signal, frame):
        import pdb
        pdb.set_trace()

 # set CPU limit and enter the debugger on CPU limit
    resource.setrlimit(resource.RLIMIT_CPU, (10, 100))
    signal.signal(signal.SIGXCPU, int_handler)

    # enter debugger at ctrl-c and ctrl-\
    signal.signal(signal.SIGINT, int_handler)
    signal.signal(signal.SIGQUIT, int_handler)
```
Setting CPU limits and/or catching SIGQUIT should offer an "acceptable" way to enter/investigate/find the culprit, but only if it's an infinite loop somewhere in tables/numexpr.

**Comment by tomkooij** [comment]
I tried a different seed.

The simulations hang  *around* the same iteration! 

Simulation 536314608_692422008 hangs:
* at iteration 27978 using seed '153957'  
* at iteration 27943 using seed '42'

results.h5 are every similar in size:
-rw-r--r--. 1 tkooij hisparc 4570072 Jun 30 22:39 result1.h5
-rw-r--r--. 1 tkooij hisparc 4574168 Jun 30 22:18 result.h5

core positions are very different:
(401.7268206123729, -572.1648929120339)
(-857.9878478581118, -225.64513048492825)

Conclusion (?): the read_where does not hang at a specific query, but hangs after a certain number of repetitive calls. 

I would guess that this is a memory problem, but memory usage is very low (77M). Perhaps some leak outside of the python VM?

I'm running this simulation overnight with the signal handler to see if SIGQUIT will start pdb. My guess is that it will not, but i'll try to report here.

**Comment by 153957** [comment]
Ok, we did have some simulations that properly went all the way to 100000, both larger and smaller simulations.. RAM should indeed not be the problem.. since it keeps using CPU I suspect some hanging loop..

**Comment by tomkooij** [comment]
Trying to catch SIGQUIT does not work: No debugger even after several minutes. So catching SIGQUIT is a bad idea, because you can only really kill the process using SIGKILL.

I reran 536314608_692422008 using seed '1042' this hangs at 27930. 

So either numpy.random.seed() is seriously flawed or the failure is not caused by a specific read_where() query.

**Comment by 153957** [comment]
Im rerunning the simulation (2 threads simultaneously) set to be interrupted at the correct iteration and for the correct station. Im going to the PhD defense of a colleague soon, Ill try stepping through the debugger when I get back.

**Comment by 153957** [comment]
This is the line that hangs:
```
> ../lib/python2.7/site-packages/tables/table.py(256)_table__where_indexed()
-> self._nslotseq = self._seqcache.setitem(seqkey, [], 1)
```

**Comment by tomkooij** [comment]
Nice work! :+1: :+1: 

This line is removed in the 3.3-dev version of pytables on github: https://github.com/PyTables/PyTables/commit/ace4ac4795cb2983d071105073228cf0a27e0f04

So perhaps just updating pytables fixes this.

**Comment by 153957** [comment]
Good that it may already be fixed.. unfortunate that it was not already fixed..

Related issue: PyTables/PyTables#351, and pull request: PyTables/PyTables#353,

**Comment by 153957** [comment]
I will install the latest develop branch in the `corsika_env` on `/data/hisparc` and rerun some simulations.

**Comment by 153957** [comment]
I've updated PyTables to v3.2 and restarted all 100 simulations.

**Comment by davidfokkema** [comment]
And? I managed just now to read all messages. What a terrible bug! The bug report sounds familiar: the empty array as return value, and a 'hang' consistent with a full table scan. Ouch! Great that you figured this all out. BTW, I love your debug tool!

**Comment by 153957** [comment]
Half of them have already finished, some of those that failed previously have already finished. I checked one which previously had only 26895 rows, did have 100k this time, indicating the problem is fixed.

**Comment by 153957** [comment]
I still do not understand why it hangs sometimes and does not at (most) other times. Most simulation runs have 0 particles in many detectors.. Perhaps it has to be one where the index already indicates 0 particles in the detector, however, I would assume that also occurs quite often. And even a 'full scan' should not take days (48 hours on long queue)..

**Comment by tomkooij** [comment]
:+1: again! You're debugging tool is epic.

It is **very** embarassing that a simple ``` conda update pytables ``` fixes this! 

Why didn't we think of that? 

I actually considered installing the latest "dev" version of pytables, but they don't even support setuptools properly. I never even considered checking for a new stable release (released six weeks ago...)

doh!

**Comment by 153957** [comment]
Only 5 still running, but their output files (`result.h5`) are still being written to, so its working fine.

**Comment by davidfokkema** [comment]
@153957 Maybe there is a difference when the ``where`` query returns zero results and when an *index* being used inside the ``where`` query returns zero results? The full table scan only happens in the latter case, I think.

**Comment by 153957** [comment]
Yes, and we use an index for all queries.. but a full table scan of a 4 MB file should not take to long..

**Comment by tomkooij** [comment]
@davidfokkema It was certainly not a full table scan that cause this:
* no response even after 48h on stoomboot
* no response from Ctrl-C (SIGQUIT) from the python VM
I suspect a crash and/or inf loop outside the python VM.

I was looking at the code last night (too hot to sleep):
According to @153957 this line hangs:
```
> ../lib/python2.7/site-packages/tables/table.py(256)_table__where_indexed()
-> self._nslotseq = self._seqcache.setitem(seqkey, [], 1)
```
This calls:https://github.com/PyTables/PyTables/blame/develop/tables/lrucacheextension.pyx#L392

This is CYTHON pre-compiled code, so a crash might be caused by some weird overflow. I cannot figure out why the 3.2.0 codes works and the 3.1.1 does not. (Because the 3.2.0 code calls the .setitem method as well **and** there are not fixes against that method.

It's all Voodoo to me. Lucily, its fixed, so my lack of understanding does not interfere with real work ;)

**Comment by davidfokkema** [comment]
Good! End-of-year stuff and struggling with an AFM denied me any chance at contributing anything substantial. Glad you figured it out!
