### ISSUE TITLE
.transformations.celestial.py uses (longitude,latitude) while cluster.py uses (latitude, longitude)

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/sapphire#91]
Another lat,lon thing..

https://github.com/HiSPARC/sapphire/blob/master/sapphire/transformations/celestial.py#L20 uses (lon, lat) cluster.py uses lat, lon

Both (lon,lat) and (lat,lon) seem to be "the standard". We should choose one and be consequent. keyword arguments could prevent this mess.

However, changing celestial.py to (lat,lon) will break existing scripts. (@SBeijen ?)

**Comment by 153957** [comment]
lat,lon is more widely used. If you google for latitude and longitude with some separator between them (e.g. 'and', ',') and in quotes to force the order you find more results with latitude first.
However, it seems astropy uses the reverse: https://github.com/astropy/astropy/blob/21de9efacb168a8e258103c626db3dabe9d069ae/astropy/coordinates/earth.py#L129

We also put latitude first when listing the GPS coordinates for a station:
http://data.hisparc.nl/show/stations/3001/2015/12/13/#stationPosition
And in the TSV download for GPS coordinates the order is also lat, lon, alt.
http://data.hisparc.nl/show/source/gps/3001/

I would argue for using lat, lon whenever order is important (i.e. not for dictionaries)

**Comment by davidfokkema** [comment]
I concur.

**Comment by 153957** [comment]
Since, as you noted, this will break the current API (not the Publicdb API but some of the calls to SAPPHiRE functions) the next release of SAPPHiRE will be at least 0.13.x
